namespace: "ibmcloud"
name: "ibmcollection"
version: "1.6.0"
readme: "README.md"
authors:
    - "Jay W Carman"
    - "Anilkumar C M"
license:
    - "MPL-2.0"
tags:
    - ibmcloud
    - cloud
    - collection
    - terraform
repository: "https://github.com/IBM-Cloud/ansible-collection-ibm"
