---
- name: Destroy transit gateways and connections.
  hosts: localhost
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml

    - name: Get resource group Info 
      ibm_resource_group_info:
        name: "{{ resource_group_name }}"
      register: resource_group_output

    - name: Save existing resource group info as fact
      set_fact:
        cacheable: True
        rg: "{{ resource_group_output.resource }}"
      when: resource_group_output.resource.id is defined
    
    - name: Get transit gateway info instance
      ibm_tg_gateway_info:
        name: "{{ tg_gateway_name}}"
      register: tg_gateway_output
    
    - name: Save existing tg-gateway info as fact
      set_fact:
        cacheable: True
        tg_gateway: "{{ tg_gateway_output.resource }}"
      when: tg_gateway_output.rc==0

    # - name: Get vpc info for tg connection
    #   ibm_is_vpc_info:
    #     name: "{{ vpc_name }}"
    #   register: vpc_output

    # - name: Save existing vpc info as fact
    #   set_fact:
    #     cacheable: True
    #     vpc: "{{ vpc_output.resource }}"
    #   when: vpc_output.rc==0
    
    # - name: Destroy tg connection  for tg gateway
    #   ibm_tg_connection:
    #     gateway: "{{ tg_gateway.id }}"
    #     network_type: "vpc"
    #     name: "{{ connection_name }}"
    #     network_id: "{{ vpc.resource_crn }}"
    #     id: "tg_gateway.connections[0].id"
    #     state: absent

    # - name: Destroy vpc for tg connection
    #   ibm_is_vpc:
    #     name: "{{ vpc_name }}"
    #     id: "{{ vpc.id }}"
    #     state: absent

    - name: Destroy transit gateway instance
      ibm_tg_gateway:
        name: "{{ tg_gateway_name}}"
        location: "{{ location }}"
        global_: "{{ global }}"
        resource_group: "{{ rg.id }}"
        id: "{{ tg_gateway.id }}"
        state: absent