---
- name: Import a certificate on a certificate manager insatnce.
  hosts: localhost
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml
    
    - name: provision certificate manager resource instance
      ibm_resource_instance:
        name: "{{ service_name }}"
        location: "{{ location }}"
        service: "cloudcerts"
        plan: "free"
      register: resource_instance_output
    
    - name: Save certificate manager resource instance as fact
      set_fact:
        cacheable: True
        cms: "{{ resource_instance_output.resource }}"
      when: resource_instance_output.rc==0

    - name: provision cms import resource.
      ibm_certificate_manager_import:
        certificate_manager_instance_id: "{{ cms.id }}"
        name: "{{ import_name }}"
        data: 
          content: "{{ lookup('file', '/Users/kavya/ca.crt') }}"
      register: cms_import_output

    - name: Save cms import resource as fact
      set_fact:
        cacheable: True
        cms_import: "{{ cms_import_output.resource }}"
      when: cms_import_output.rc==0

    - name: provision cms order resource
      ibm_certificate_manager_order:
        certificate_manager_instance_id: "{{ cms.id }}"
        name: "{{ order_name }}"
        description: "Order Certificate"
        domains: 
          - "cis-terraform.com"
        rotate_keys: "{{ rotate_keys }}"
        domain_validation_method: "dns-01"
        dns_provider_instance_crn: "{{  cis_id }}"
      register: cms_order_output

    - name: Save cms order info as fact
      set_fact:
        cacheable: True
        cms_order: "{{ cms_order_output.resource }}"
      when: cms_order_output.rc==0   

    - name: Get cms certificate info
      ibm_certificate_manager_certificate_info:
        certificate_manager_instance_id: "{{ cms.id }}"
        name: "{{ import_name }}"
      register: certificate_output

    - name: Save cms certificate info as fact
      set_fact:
        cacheable: True
        certificate_info: "{{ certificate_output.resource }}"
      when: certificate_output.rc==0
    
    - name: Get cms certificates info
      ibm_certificate_manager_certificates_info:
        certificate_manager_instance_id: "{{ cms.id }}"
      register: certificates_output

    - name: Save cms certificates list info as fact
      set_fact:
        cacheable: True
        certificates_info: "{{ certificates_output.resource }}"
      when: certificates_output.rc==0
     