---
- name: Destroy cms certificates and cms instance.
  hosts: localhost
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml

    - name: Get Resource id details
      ibm_resource_instance_info:
        name: "{{ service_name }}"
      register: resource_info

    - name: Get resource
      set_fact:
        cacheable: True
        cms: "{{ resource_info.resource }}"

    - name: Get certificate
      ibm_certificate_manager_certificate_info:
        certificate_manager_instance_id: "{{ cms.id }}"
        name: "{{ import_name }}"
      register: certificate1_output

    - name: Save cms imported certificate info as fact
      set_fact:
        cacheable: True
        certificate1_info: "{{ certificate1_output.resource }}"
      when: certificate1_output.rc==0


    - name: Get 2nd certificate
      ibm_certificate_manager_certificate_info:
        certificate_manager_instance_id: "{{ cms.id }}"
        name: "{{ order_name }}"
      register: certificate2_output

    - name: Save cms ordered certificate info as fact
      set_fact:
        cacheable: True
        certificate2_info: "{{ certificate2_output.resource }}"
      when: certificate2_output.rc==0

    - name: destroy imported certificate
      ibm_certificate_manager_import:
        certificate_manager_instance_id: "{{ cms.id }}"
        name: "{{ import_name }}"
        data: 
          content: "{{ lookup('file', '/Users/kavya/ca.crt') }}"
        id: certificate1_info.certificate_details[0].cert_id
        state: absent

    - name: destroy ordered certificate
      ibm_certificate_manager_order:
        certificate_manager_instance_id: "{{ cms.id }}"
        name: "{{ order_name }}"
        description: "Order Certificate"
        domains: 
          - "cis-terraform.com"
        rotate_keys: "{{ rotate_keys }}"
        domain_validation_method: "dns-01"
        dns_provider_instance_crn: "{{  cis_id }}"
        id: certificate2_info.certificate_details[0].cert_id
        state: absent


    - name: destroy cms resource instance
      ibm_resource_instance:
        name: "{{ service_name }}"
        location: "{{ location }}"
        service: "cloudcerts"
        plan: "free"
        id: "{{ cms.id }}"
        state: absent
      register: resource_instance_output