---
- name: List Power Virtual Server Cloud Images
  hosts: localhost
  collections:
   - ibm.cloudcollection
  vars:
    pi_cloud_instance_id: "YOUR PI CLOUD INSTANCE ID"

  tasks:
    - ibm_pi_images_info:
        pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"
      register: images_list

    - debug:
        var: images_list.resource.image_info |
             items2dict(key_name='name', value_name='id')
