---
- name: Resource Group Creation.
  hosts: localhost
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml

    - name: Check resource group Exists
      ibm_resource_group_info:
        name: "{{ resource_group_name }}"
      failed_when: 
         - resource_group_output.rc != 0
         - '"ResourceGroupDoesnotExist" not in resource_group_output.stderr'     
      register: resource_group_output

    - name: Save existing resource group info as fact
      set_fact:
        cacheable: True
        resource_group: "{{ resource_group_output.resource }}"
      when: resource_group_output.resource.id is defined

    - name: Create resource Group
      ibm_resource_group:
        name: "{{ resource_group_name }}"
      register: rg_create_output
      when: resource_group is not defined

    - name: Save newly created resource group info as fact
      set_fact:
        cacheable: True
        resource_group: "{{ rg_create_output.resource }}"
      when: rg_create_output.resource.id is defined

    - name: Print Resource group info 
      debug:
        msg: "Resource Group : {{ resource_group }}"

        

      