---
- name: Translate network interface(s) security group name(s) to ID
  set_fact:
    network_interfaces_sgs: "{{ (network_interfaces_sgs | default({})) | combine({interface_index: ((network_interfaces_sgs[interface_index]|default([])) + [name_to_id])}) }}"
  loop: "{{ interface.security_groups }}"
  vars:
    name_to_id: "{{ security_group_map[item] | default(item) }}"
  when: interface.security_groups is defined
